name: publish

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org'
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-latest-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - run: yarn --frozen-lockfile
      - run: yarn nx run-many --all --target build
      - run: for dir in dist/libs/*; do npm publish --access public "$dir"; done
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
